# Generated by Django 2.0.7 on 2019-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='profession',
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
