# Generated by Django 2.0.7 on 2019-05-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0002_auto_20190520_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_info_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('profession', models.CharField(choices=[('webd', 'Web Developer'), ('datasci', 'Data Scientist')], max_length=2)),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
