# Generated by Django 2.0.7 on 2019-05-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0003_auto_20190521_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info_add',
            name='profession',
            field=models.CharField(choices=[('webd', 'Web Developer'), ('datasci', 'Data Scientist')], max_length=20),
        ),
    ]
