# Generated by Django 2.0.7 on 2019-05-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0004_auto_20190521_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info_add',
            name='profession',
            field=models.CharField(max_length=50),
        ),
    ]
